src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'Un compte lié à cette email existe déjà')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    #[ORM\Column(length: 255)]
    private ?string $phone = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\OneToOne(mappedBy: 'manager', cascade: ['persist', 'remove'])]
    private ?Club $club = null;

    #[ORM\ManyToOne(inversedBy: 'player')]
    private ?Team $team = null;

    #[ORM\OneToMany(mappedBy: 'coach', targetEntity: Team::class)]
    private Collection $teams;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $birth = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $post = null;

    #[ORM\OneToMany(mappedBy: 'player', targetEntity: TrainingPresence::class)]
    private Collection $trainingPresences;

    public function __construct()
    {
        $this->teams = new ArrayCollection();
        $this->trainingPresences = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
//        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getClub(): ?Club
    {
        return $this->club;
    }

    public function setClub(?Club $club): self
    {
        // unset the owning side of the relation if necessary
        if ($club === null && $this->club !== null) {
            $this->club->setManager(null);
        }

        // set the owning side of the relation if necessary
        if ($club !== null && $club->getManager() !== $this) {
            $club->setManager($this);
        }

        $this->club = $club;

        return $this;
    }

    public function getTeam(): ?Team
    {
        return $this->team;
    }

    public function setTeam(?Team $team): self
    {
        $this->team = $team;

        return $this;
    }

    /**
     * @return Collection<int, Team>
     */
    public function getTeams(): Collection
    {
        return $this->teams;
    }

    public function addTeam(Team $team): self
    {
        if (!$this->teams->contains($team)) {
            $this->teams->add($team);
            $team->setCoach($this);
        }

        return $this;
    }

    public function removeTeam(Team $team): self
    {
        if ($this->teams->removeElement($team)) {
            // set the owning side to null (unless already changed)
            if ($team->getCoach() === $this) {
                $team->setCoach(null);
            }
        }

        return $this;
    }

    public function getBirth(): ?\DateTimeInterface
    {
        return $this->birth;
    }

    public function setBirth(?\DateTimeInterface $birth_date): self
    {
        $this->birth = $birth_date;

        return $this;
    }

    public function getPost(): ?string
    {
        return $this->post;
    }

    public function setPost(?string $post): self
    {
        $this->post = $post;

        return $this;
    }

    /**
     * @return Collection<int, TrainingPresence>
     */
    public function getTrainingPresences(): Collection
    {
        return $this->trainingPresences;
    }

    public function addTrainingPresence(TrainingPresence $trainingPresence): self
    {
        if (!$this->trainingPresences->contains($trainingPresence)) {
            $this->trainingPresences->add($trainingPresence);
            $trainingPresence->setPlayer($this);
        }

        return $this;
    }

    public function removeTrainingPresence(TrainingPresence $trainingPresence): self
    {
        if ($this->trainingPresences->removeElement($trainingPresence)) {
            // set the owning side to null (unless already changed)
            if ($trainingPresence->getPlayer() === $this) {
                $trainingPresence->setPlayer(null);
            }
        }

        return $this;
    }
}

templates/partials/_club_card.html.twig
<div class="card-club card-club-back box-shadow">

    <a class='link' href="{{ path('app_club_show', {'id': club.id}) }}"></a>
    <div class="card-title-club">
        <p>CLUB</p>
    </div>

    <div class="row">
        <div class="col-md-4 mb-3 mb-md-0">
            <div class="card-image">
                <img class="img50" src="{{ asset('uploads/images/' ~ club.logo) }}" alt="Logo du club">
            </div>
        </div>
        <div class="col-md-8">
            <div class="card-content">

                <h2 class="card-text bold">{{ club.name }}</h2>
                <p><span class="bold">Président : </span>{{ club.manager.firstname }} {{ club.manager.lastname }}</p>
                <p><span class="bold">Téléphone : </span>{{ club.phone }}</p>
                <p><span class="bold">Adresse : </span> {{ club.adress }}</p>
                <p><span class="bold">Nombres d'équipes : </span> {{ club.team | length }}</p>

                {% if is_granted('ROLE_MANAGER') %}
                    <p class="d-none d-sm-block">
                        <a class="z-1 position-absolute custom-btn"
                           href="{{ path('app_club_edit', {'id': club.id}) }}">Modifier</a>
                    </p>
                    <p class="d-block d-sm-none mx-3 mt-5">
                        <a class="z-1 position-relative custom-btn"
                           href="{{ path('app_club_edit', {'id': club.id}) }}">Modifier</a>
                    </p>
                {% endif %}

            </div>
        </div>
    </div>
</div>

templates/partials/_player_card.html.twig
<div class="card-club card-team-back d-flex flex-column box-shadow h-100">
    <a class="link"
       href="{{ path('app_user_show', {'id': player.id}) }}"></a>
    <div class="card-image d-flex justify-content-center mb-3">
        <img class="img100" src="{{ asset('build/images/abstract-user-flat-4.svg') }}" alt="Logo du club">
    </div>
    <div class="card-content">

        <h4 class="card-text text-center">{{ player.firstname }}<br><span
                    class="text-uppercase">{{ player.lastname }}</span>
        </h4>

        <div class="d-flex flex-column justify-content-center align-items-center my-2">
            {% if player.post %}
            <p><span class="fw-bolder">Poste :</span> {{ player.post }}</p>
            {% endif %}
            {% set age = date().diff(date(player.birth)).y %}
            {% if player.birth %}
            <p><span class="fw-bolder">Age :</span> {{ age }}</p>
            {% endif %}
        </div>
    </div>
</div>

templates/partials/_team_card.html.twig
<div class="d-flex card-club card-team-back box-shadow">

    <a class="link" href="{{ path('app_team_show', {'id': team.id}) }}"></a>
    <div class="card-title-team">
        <p>ÉQUIPE</p>
    </div>
    <div class="card-image col-4 d-flex justify-content-center align-items-center">
        <img class="img50" src="{{ asset('uploads/images/' ~ team.photo) }}" alt="Logo du club">
    </div>
    <div class="card-content col-8">

        <h2 class="card-text">{{ team.category }} - {{ team.level }}</h2>
        {% for coach in team.player %}
            {% if coach.roles[0] == "ROLE_COACH" %}
                <p class="z-1 position-relative d-inline-block"><a class="dark-color"
                                                                   href="{{ path('app_user_show', {'id': coach.id}) }}"><span
                                class="fw-bolder">Coach</span>
                        : {{ coach.firstname }} {{ coach.lastname }} </a></p>
            {% endif %}
        {% endfor %}

        {% if team.player.count > 0 %}
            <p><span class="fw-bolder">Nombre de joueurs :</span> {{ team.player | length - 1 }}</p>
        {% endif %}

        {% if is_granted('ROLE_MANAGER') or is_granted('ROLE_COACH') %}
            <p>
                <a class="z-2 position-relative custom-btn-light"
                   href="{{ path('app_team_edit', {'id': team.id}) }}">Modifier</a>
            </p>
        {% endif %}

    </div>
</div>

templates/partials/_team_cardTest.html.twig
<div class="card-club card-team-back box-shadow">

    <a class="link" href="{{ path('app_team_show', {'id': team.id}) }}"></a>
    <div class="card-title-team">
        <p>ÉQUIPE</p>
    </div>

    <div class="row">
        <div class="col-md-4 mb-3 mb-md-0">
            <div class="card-image">
                <img class="img50" src="{{ asset('uploads/images/' ~ team.photo) }}" alt="Photo de l'équipe">
            </div>
        </div>
        <div class="col-md-8">
            <div class="card-content">

                <h2 class="card-text bold">{{ team.category }} - {{ team.level }}</h2>
                {% for coach in team.player %}
                    {% if coach.roles[0] == "ROLE_COACH" %}
                        <p class="z-1 position-relative d-inline-block"><a class="dark-color"
                                                                           href="{{ path('app_user_show', {'id': coach.id}) }}"><span
                                        class="bold">Coach</span>
                                : {{ coach.firstname }} {{ coach.lastname }} </a></p>
                    {% endif %}
                {% endfor %}

                {% if team.player.count > 0 %}
                    <p><span class="bold">Nombre de joueurs :</span> {{ team.player | length - 1 }}</p>
                {% endif %}

                {% if is_granted('ROLE_MANAGER') or is_granted('ROLE_COACH') %}
                    <p class="d-none d-sm-block">
                        <a class="z-2 position-absolute custom-btn-light"
                           href="{{ path('app_team_edit', {'id': team.id}) }}">Modifier</a>
                    </p>
                    <p class="d-block d-sm-none mx-3 mt-5">
                        <a class="z-2 position-relative custom-btn-light"
                           href="{{ path('app_team_edit', {'id': team.id}) }}">Modifier</a>
                    </p>
                {% endif %}

            </div>
        </div>
    </div>
</div>

templates/partials/_training_card.html.twig
<div class="card-club card-team-back d-flex box-shadow">

    <a class="link" href="{{ path('app_training_show', {'id': training.id}) }}"></a>

    <p>{{ training.id }}</p>
    <p>{{ training.date ? training.date|date('Y-m-d H:i:s') : '' }}</p>
    <p>{{ training.place }}</p>
    <p>{{ training.team.club.name }}</p>
    <p>{{ training.team.category }}</p>
    <p>{{ training.team.level }}</p>
    <p>{{ training.team.id }}</p>
    <p>{{ training.info }}</p>
        <a class="dark-color" href="{{ path('app_training_edit', {'id': training.id}) }}">edit</a>

    {% for player in training.team.player %}
        <p>
            {{ player.firstname }}  {{ player.lastname }}
        </p>
    {% endfor %}


</div>

templates/partials/footer.html.twig
<div class="bg-grey">
    <footer class="main-footer">
        <div class="container-fluid">
            <div class="row nous-rejoindre">
                <div class="col-md-6">
                    <p><span>Rejoignez plus de 10 000 clubs</span><br> et 90 000 équipes
                        en vous inscrivant dès aujourd’hui.</p>
                </div>
                <div class="col-md-6 d-flex justify-content-end align-items-center">
                    <a class="d-inline-block custom-btn text-center" href="#">Inscrire mon équipe</a>
                    <a class="d-inline-block custom-btn text-center ms-3" href="#">Inscrire mon club</a>
                </div>
            </div>
            <div class="row middle-footer">
                <div class="col-md-3">
                    <h5>Langues</h5>
                    <ul>
                        <li>English</li>
                        <li>Français</li>
                        <li>Espanol</li>
                        <li>Portugues</li>
                        <li>Italiano</li>
                        <li>Deutsch</li>
                        <li>Nederland</li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <h5>A propos de nous</h5>
                    <ul>
                        <li>Qui sommes-nous ?</li>
                        <li>Presse</li>
                        <li>Nous rejoindre</li>
                        <li>Plan du site</li>
                        <li>Blog</li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <h5>Vous avez une question ?</h5>
                    <ul>
                        <li>FAQ</li>
                        <li>Envoyez-nous un mail</li>
                        <li>+33 1 02 03 04 05</li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <h5>Fonctionnalités</h5>
                    <ul>
                        <li>Gestion d'équipe</li>
                        <li>Gestion de club</li>
                        <li>Retrouvez tout les sports</li>
                        <li>Football</li>
                        <li>Rugby</li>
                        <li>Volley</li>
                        <li>Basket</li>
                    </ul>
                </div>
            </div>
            <div class="row bottom-footer d-flex align-items-center">
                <div class="col-md-6 d-flex justify-content-between justify-content-md-start">
                    <a href="#">Mentions légales</a>
                    <a href="#">CGU</a>
                    <a href="#">Protection des données</a>
                </div>
                <div class="col-md-6">
                    <ul class="d-flex justify-content-md-end justify-content-between">
                        <li><a href="#"><img src="{{ asset('build/images/picto_facebook.png') }}"></a>
                        </li>
                        <li><a href="#"><img src="{{ asset('build/images/picto_twitter.png') }}"></a>
                        </li>
                        <li><a href="#"><img src="{{ asset('build/images/picto_linkedin.png') }}"></a>
                        </li>
                        <li><a href="#"><img src="{{ asset('build/images/picto_youtube.png') }}"></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
</div>

templates/partials/header.html.twig
<header id="nav">
    <nav class="container">
        <div class="container">
            <a class="" href="{{ path('app_home') }}">
                <img class="logo" src="{{ asset('build/images/logo.png') }}" alt="Logo You Coach">
            </a>
            <ul class="navbar-nav">
                {% if is_granted('ROLE_MANAGER') %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            {{ app.user.firstname }} {{ app.user.lastname }}
                        </a>
                        <ul class="dropdown-menu">
                            <li class="border-bottom">
                                <p class="dropdown-item">MANAGER</p>
                            </li>
                            <li><a class="dropdown-item" href="{{ path('app_user_edit', {'id' : app.user.id}) }}">Mon
                                    compte</a></li>
                            {% if app.user.club %}
                                <li><a class="dropdown-item"
                                       href="{{ path('app_club_show', {'id': app.user.club.id}) }}">Mon club</a></li>
                                <li><a class="dropdown-item"
                                       href="{{ path('app_user_new') }}">Nouveau membre</a></li>
                            {% else %}
                                <li><a class="dropdown-item" href="{{ path('app_club_new') }}">Inscrire mon club</a>
                                </li>
                            {% endif %}
                            <li><a class="dropdown-item" href="{{ path('app_logout') }}">Me déconnecter</a></li>
                        </ul>
                    </li>
                {% elseif is_granted('ROLE_PLAYER') %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            {{ app.user.firstname }} {{ app.user.lastname }}
                        </a>
                        <ul class="dropdown-menu">
                            <li class="border-bottom">
                                <p class="dropdown-item">JOUEUR</p>
                            </li>
                            <li><a class="dropdown-item" href="{{ path('app_user_edit', {'id' : app.user.id}) }}">Mon
                                    compte</a></li>
                            <li><a class="dropdown-item"
                                   href="{{ path('app_club_show', {'id' : app.user.team.club.id}) }}">Mon club</a></li>
                            <li><a class="dropdown-item" href="{{ path('app_logout') }}">Me déconnecter</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('app_login') }}">Connexion</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link ms-3 custom-btn" href="{{ path('app_register') }}">Inscrire mon équipe</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>

templates/partials/new-header.html.twig
<header>
    <nav {% if app.request.attributes.get('_route') == 'app_home' %} class="nav-home" id="nav" {% endif %}>
        <div class="container bloc-nav">
            <a href="{{ path('app_home') }}" class="logo-link">
                <img class="logo" src="{{ asset('build/images/logo.png') }}" alt="logo">
            </a>
            <div class="nav-links">
                <ul>
                    {% if is_granted('ROLE_MANAGER') %}
                        {% if app.user.club %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ path('app_user_edit', {'id' : app.user.id}) }}">Mon
                                    compte</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ path('app_club_show', {'id': app.user.club.id}) }}">Mon
                                    club</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ path('app_user_new') }}">Nouveau membre</a>
                            </li>

                        {% else %}
                            {% if app.user.verified %}
                                <li class="nav-item">
                                    <a class="nav-link custom-btn" href="{{ path('app_club_new') }}">Inscrire mon
                                        club</a>
                                </li>
                            {% endif %}
                        {% endif %}

                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('app_logout') }}">
                                <i class="fa-solid fa-arrow-right-from-bracket"></i>
                            </a>
                        </li>

                    {% elseif is_granted('ROLE_PLAYER') %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('app_user_edit', {'id' : app.user.id}) }}">Mon compte</a>
                        </li>
                        {% if app.user.verified %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ path('app_club_show', {'id' : app.user.team.club.id}) }}">Mon
                                    club</a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class=nav-link" href="{{ path('app_logout') }}">
                                <i class="fa-solid fa-arrow-right-from-bracket"></i>
                            </a>
                        </li>

                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('app_login') }}">Connexion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link custom-btn" href="{{ path('app_register') }}">Inscrire mon club</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
            <img class="menu-burger" src="{{ asset('build/images/menu-btn.png') }}" alt="Menu burger">
        </div>
    </nav>
</header>